import type { NavItem } from "@/types"
import { FileIcon, PersonIcon } from "@radix-ui/react-icons"
import { Briefcase, KeyIcon } from "lucide-react"

export const videos = [
  {
    clientName: "Ayres Management, L.P. 401(k) Savings & Investment Plan",
    videoId: "9",
    fiduciaryTraining: "Status",
    lastModified: "1 day ago",
    clientColor: "#000000",
    image: "/client-logo/ayres.png",
    advisorImage: "/ty-rogers.jpg",
    videoUrl: "https://waypoint-bucket.s3.us-east-2.amazonaws.com/AYRES+Test.mp4",
    externalLink: "https://waypointfas.com/ayres-hotels/",
    isLegacyPlan: true,
    analytics: [
      {
        videoType: "Educational Video",
        pageViews: 33,
        videoPlays: 55,
        videoCompletes: 66,
        uniqueVisitors: 44,
        date: "5/31/2024",
      },
      {
        videoType: "Plan Video",
        pageViews: 53,
        videoPlays: 77,
        videoCompletes: 33,
        uniqueVisitors: 99,
        date: "6/4/2024",
      },
    ],
    items: {
      title: "Ayres Management, L.P. 401(k) Savings & Investment Plan",
      image: "/client-logo/ayres.png",
      advisorImage: "/ty-rogers.jpg",
      eligibility: {
        waiting_period:
          "Employees age 21 or older who have completed 1,000 hours of service are eligible to enter the plan on the next semi annual entry date, January and July 1st",
      },
      employee_contributions: {
        auto_enrollment: "No",
        auto_increase: "No",
        safe_harbor: "No",
        after_tax_contributions: "No",
        mandatory_contributions: "No",
        roth_contributions: "Yes",
      },
      employer_contributions: {
        match: "Fifty Percent Match, 6%",
        safe_harbor: "N/A",
        non_elective: "N/A",
      },
      vesting_and_operations: {
        vesting: "6 Year Graded",
        qdia: "Yes",
        target_date: "Yes",
        models: "Yes",
        loans_permitted: "Yes",
        hardships_permitted: "Yes",
        sd_brokerage_account: "No",
        managed_accounts: "No",
      },
      data: [
        {
          id: 1,
          title: "Plan Investment Advisor",
          subTitle: "Ty Rogers",
          email: "401ksupport@waypoint.com",
          phone: "(877) 757-3263",
          image: "/logo-2.png",
          icon: FileIcon,
        },
        {
          id: 2,
          title: "Account Access / Enroll",
          subTitle: "OneAmerica",
          website: "https://oneamerica.com",
          phone: "(800) 249-6269",
          planId: "G38412",
          image: "/one-america.png",
          icon: KeyIcon,
        },
        {
          id: 3,
          title: "Point of Contact",
          subTitle: "Sindy Gutierrez",
          email: "sindy@ayresgroup.net",
          phone: "(714) 850-0409",
          image: "/client-logo/ayres-2.png",
          icon: PersonIcon,
        },
      ],
    },
    // Add plan collateral for Ayres client
    planCollateral: {
      items: [
        {
          title: "Portal Poster",
          english: { file: "/flyers/portal-en.pdf", image: "/content-library/portal-poster.jpg" },
          spanish: { file: "/flyers/portal-es.pdf", image: "/content-library/portal-poster.jpg" },
        },
        {
          title: "Meeting Announcement Poster",
          english: { file: "/flyers/meeting-announcements-en.pdf", image: "/content-library/meeting-announcement.jpg" },
          spanish: { file: "/flyers/meeting-announcements-es.pdf", image: "/content-library/meeting-announcement.jpg" },
        },
        {
          title: "Missing Retirement Poster",
          english: { file: "/flyers/missing-en.pdf", image: "/content-library/missing-retirement.jpg" },
          spanish: { file: "/flyers/missing-es.pdf", image: "/content-library/missing-retirement.jpg" },
        },
      ],
    },
  },
  {
    clientName: "KTI Inc. 401(k) Profit Sharing Plan & Trust",
    videoId: "1",
    fiduciaryTraining: "Status",
    lastModified: "15 days ago",
    clientColor: "#0B264E",
    image: "/client-logo/KTI.png",
    videoUrl: "https://waypoint-bucket.s3.us-east-2.amazonaws.com/401k-example.mp4",
    externalLink: "https://waypointfas.com/thompson-pipe-group-kti/",
    isLegacyPlan: true,
    analytics: [
      {
        videoType: "Educational Video",
        pageViews: 34,
        videoPlays: 66,
        videoCompletes: 88,
        uniqueVisitors: 77,
        date: "5/31/2024",
      },
      {
        videoType: "Plan Video",
        pageViews: 43,
        videoPlays: 10,
        videoCompletes: 55,
        uniqueVisitors: 88,
        date: "6/4/2024",
      },
    ],
    items: {
      title: "KTI Inc. 401(k) Profit Sharing Plan and Trust",
      image: "/client-logo/KTI.png",
      eligibility: {
        waiting_period:
          "After 3 months of service employees age 18 or older can enter the plan at the beginning of the next month",
      },
      employee_contributions: {
        auto_enrollment: "3%, after 3 months",
        auto_increase: "1% up to 10%",
        safe_harbor: "Yes",
        after_tax_contributions: "No",
        mandatory_contributions: "No",
        roth_contributions: "Yes",
      },
      employer_contributions: {
        match: "N/A",
        safe_harbor: "100% match on the first 3%, and a 50% match on the next 2%",
        non_elective: "N/A",
        // waiting_period: "3 months",
      },
      vesting_and_operations: {
        vesting: "100% after two years",
        qdia: "Yes",
        target_date: "Yes",
        models: "No",
        loans_permitted: "Yes",
        hardships_permitted: "Yes",
        sd_brokerage_account: "No",
        managed_accounts: "No",
      },
      data: [
        {
          id: 1,
          title: "Plan Investment Advisor",
          subTitle: "Ty Rogers",
          email: "401ksupport@waypoint.com",
          phone: "(877) 757-3263",
          image: "/logo-2.png",
          icon: Briefcase,
        },
        {
          id: 2,
          title: "Account Access / Enroll",
          subTitle: "Transamerica",
          website: "https://www.transamerica.com/portal/",
          phone: "(800) 401-8726",
          image: "/transamerica.png",
          icon: KeyIcon,
        },
        // {
        //   id: 3,
        //   title: "Human Resources",
        //   subTitle: "HR Person",
        //   email: "hr@person.com",
        //   phone: "(818) 555-5555",
        //   image: "",
        //   icon: PersonIcon,
        // },
      ],
    },
  },
  {
    clientName: "Piazza Family Restaurants 401(k) Plan",
    videoId: "2",
    fiduciaryTraining: "Status",
    lastModified: "4 months ago",
    clientColor: "#000000",
    image: "/client-logo/piazza.png",
    externalLink: "https://waypointfas.com/piazza-family-restaurants/",
    isLegacyPlan: true,
    analytics: [
      {
        videoType: "Educational Video",
        pageViews: 15,
        videoPlays: 44,
        videoCompletes: 22,
        uniqueVisitors: 99,
        date: "5/31/2024",
      },
      {
        videoType: "Plan Video",
        pageViews: 96,
        videoPlays: 22,
        videoCompletes: 88,
        uniqueVisitors: 55,
        date: "6/1/2024",
      },
    ],
    items: {
      title: "Piazza Family Restaurants 401(k) Plan",
      image: "/client-logo/piazza.png",
      eligibility: {
        waiting_period:
          "After 6 months of service employees age 21 or older can enter the plan at the beginning of the next calendar quarter",
      },
      employee_contributions: {
        auto_enrollment: "5%, after 6 months",
        auto_increase: "1% up to 10 %",
        safe_harbor: "No",
        after_tax_contributions: "No",
        mandatory_contributions: "No",
        roth_contributions: "Yes",
      },
      employer_contributions: {
        match: "Custom Match, A percentage of elective contributions determined from year to year.",
        safe_harbor: "N/A",
        non_elective: "Discretionary Employer Contributions: discretionary",
        // waiting_period:"1000 Hours",
        // waiting_period_sub:"1000 Hours"
      },
      vesting_and_operations: {
        vesting: "6 Year Graded",
        qdia: "No",
        target_date: "No",
        models: "No",
        loans_permitted: "No",
        hardships_permitted: "Yes",
        sd_brokerage_account: "No",
        managed_accounts: "No",
      },
      data: [
        {
          id: 1,
          title: "Plan Investment Advisor",
          subTitle: "Ty Rogers",
          email: "401ksupport@waypoint.com",
          phone: "(877) 757-3263",
          image: "/logo-2.png",
          icon: FileIcon,
        },
        {
          id: 2,
          title: "Account Access / Enroll",
          subTitle: "Transamerica",
          website: "https://transamerica.com",
          phone: "(800) 401-8726",
          image: "/transamerica.png",
          icon: KeyIcon,
        },
      ],
    },
  },
  {
    clientName: "Pursue Health, LLC Retirement Savings Plan",
    videoId: "3",
    fiduciaryTraining: "Status",
    lastModified: "6 days ago",
    clientColor: "#0E61BB",
    image: "/client-logo/pursue-health-removebg.png",
    analytics: [
      {
        videoType: "Educational Video",
        pageViews: 84,
        videoPlays: 66,
        videoCompletes: 22,
        uniqueVisitors: 33,
        date: "5/31/2024",
      },
      {
        videoType: "Plan Video",
        pageViews: 40,
        videoPlays: 10,
        videoCompletes: 44,
        uniqueVisitors: 99,
        date: "6/4/2024",
      },
    ],
    items: {
      title: "Pursue Health, LLC Retirement Savings Plan",
      image: "/client-logo/pursue-health-removebg.png",
      eligibility: {
        waiting_period: "Employees will enter the plan after meeting all eligibility requirements",
      },
      employee_contributions: {
        auto_enrollment: "3%, after 3 months",
        auto_increase: "No",
        safe_harbor: "No",
        after_tax_contributions: "No",
        mandatory_contributions: "No",
        roth_contributions: "Yes",
      },
      employer_contributions: {
        match: "N/A",
        safe_harbor: "N/A",
        non_elective: "N/A",
        // waiting_period: "1000 Hours, these contributions will begin on the next payroll",
      },
      vesting_and_operations: {
        vesting: "N/A",
        qdia: "Yes",
        target_date: "No",
        models: "Yes",
        loans_permitted: "Yes",
        hardships_permitted: "Yes",
        sd_brokerage_account: "No",
        managed_accounts: "No",
      },
      data: [
        {
          id: 1,
          title: "Plan Investment Advisor",
          subTitle: "Ty Rogers",
          email: "401ksupport@waypoint.com",
          phone: "(877) 757-3263",
          image: "/logo-2.png",
          icon: FileIcon,
        },
        {
          id: 2,
          title: "Account Access / Enroll",
          subTitle: "OneAmerica",
          website: "https://oneamerica.com",
          phone: "(800) 249-6269",
          planId: "G38848",
          image: "/one-america.png",
          icon: KeyIcon,
        },
        // {
        //   id: 3,
        //   title: "Human Resources",
        //   subTitle: "HR Person",
        //   email: "hr@person.com",
        //   phone: "(818) 555-5555",
        //   image: "",
        //   icon: PersonIcon,
        // },
      ],
    },
  },
  {
    clientName: "Precision Optical 401(k) Retirement Savings Plan",
    videoId: "4",
    fiduciaryTraining: "Status",
    lastModified: "4 days ago",
    clientColor: "#013365",
    image: "/client-logo/precision-optical.png",
    externalLink: "https://waypointfas.com/precision-optical/",
    isLegacyPlan: true,
    analytics: [
      {
        videoType: "Educational Video",
        pageViews: 23,
        videoPlays: 22,
        videoCompletes: 77,
        uniqueVisitors: 11,
        date: "5/31/2024",
      },
      {
        videoType: "Plan Video",
        pageViews: 45,
        videoPlays: 55,
        videoCompletes: 66,
        uniqueVisitors: 88,
        date: "6/1/2024",
      },
    ],
    items: {
      title: "Precision Optical 401(k) Retirement Savings Plan",
      image: "/client-logo/precision-optical.png",
      eligibility: {
        waiting_period:
          "After 3 months of service employees age 18 or older can enter the plan at the beginning of the next month",
      },
      employee_contributions: {
        auto_enrollment: "No",
        auto_increase: "No",
        safe_harbor: "No",
        after_tax_contributions: "No",
        mandatory_contributions: "No",
        roth_contributions: "Yes",
      },
      employer_contributions: {
        match: "Custom Match",
        safe_harbor: "N/A",
        non_elective: "N/A",
        // waiting_period: "1000 Hours, these contributions will begin on the next payroll",
      },
      vesting_and_operations: {
        vesting: "5 Years",
        qdia: "Yes",
        target_date: "Yes",
        models: "Yes",
        loans_permitted: "Yes",
        hardships_permitted: "Yes",
        sd_brokerage_account: "No",
        managed_accounts: "No",
      },
      data: [
        {
          id: 1,
          title: "Plan Investment Advisor",
          subTitle: "Ty Rogers",
          email: "401ksupport@waypoint.com",
          phone: "(877) 757-3263",
          image: "/logo-2.png",
          icon: FileIcon,
        },
        {
          id: 2,
          title: "Account Access / Enroll",
          subTitle: "OneAmerica",
          website: "https://oneamerica.com",
          phone: "(800) 249-6269",
          planId: "G38410",
          image: "/one-america.png",
          icon: KeyIcon,
        },
      ],
    },
  },
  {
    clientName: "Graiwer & Kaplan LLP 401(k) Plan",
    videoId: "5",
    fiduciaryTraining: "Status",
    lastModified: "12 days ago",
    clientColor: "#0B264E",
    image: "/client-logo/graiwer_kaplan.png",
    externalLink: "https://waypointfas.com/graiwer-kaplan-llp/",
    isLegacyPlan: true,
    analytics: [
      {
        videoType: "Educational Video",
        pageViews: 36,
        videoPlays: 55,
        videoCompletes: 11,
        uniqueVisitors: 66,
        date: "5/31/2024",
      },
      {
        videoType: "Plan Video",
        pageViews: 47,
        videoPlays: 44,
        videoCompletes: 88,
        uniqueVisitors: 55,
        date: "6/1/2024",
      },
    ],
    items: {
      title: "Graiwer & Kaplan LLP 401(k) Plan",
      image: "/client-logo/graiwer_kaplan.png",
      eligibility: {
        waiting_period:
          "After 3 months of service employees age 21 or older can enter the plan at the beginning of the next month",
      },
      employee_contributions: {
        auto_enrollment: "4%, after 3 months",
        auto_increase: "2% up to 10 %",
        safe_harbor: "No",
        after_tax_contributions: "No",
        mandatory_contributions: "No",
        roth_contributions: "Yes",
      },
      employer_contributions: {
        match:
          "Custom Match, An amount equal to 25% of your Elective Deferral which does not exceed 4% of your Compensation",
        safe_harbor: "N/A",
        non_elective: "Discretionary Profit Sharing Contributions: discretionary",
        waiting_period: "1000 Hours, these contributions will begin on the next payroll",
      },
      vesting_and_operations: {
        vesting: "5 Years",
        qdia: "Yes",
        target_date: "Yes",
        models: "No",
        loans_permitted: "Yes",
        hardships_permitted: "Yes",
        sd_brokerage_account: "No",
        managed_accounts: "No",
      },
      data: [
        {
          id: 1,
          title: "Plan Investment Advisor",
          subTitle: "Ty Rogers",
          email: "401ksupport@waypoint.com",
          phone: "(877) 757-3263",
          image: "/logo-2.png",
          icon: FileIcon,
        },
        {
          id: 2,
          title: "Account Access / Enroll",
          subTitle: "Paychex",
          website: "https://paychexflex.com",
          phone: "(877) 244-1771",
          image: "/paychex.png",
          icon: KeyIcon,
        },
        // {
        //   id: 3,
        //   title: "Human Resources",
        //   subTitle: "HR Person",
        //   email: "hr@person.com",
        //   phone: "(818) 555-5555",
        //   image: "",
        //   icon: PersonIcon,
        // },
      ],
    },
  },
  {
    clientName: "Craig Realty Group Retirement Savings Plan",
    videoId: "6",
    fiduciaryTraining: "Status",
    lastModified: "14 days ago",
    clientColor: "#4A2365",
    image: "/client-logo/craig_realty.png",
    externalLink: "https://waypointfas.com/craig-realty-group/",
    isLegacyPlan: true,
    analytics: [
      {
        videoType: "Educational Video",
        pageViews: 59,
        videoPlays: 6,
        videoCompletes: 8,
        uniqueVisitors: 3,
        date: "5/31/2024",
      },
      {
        videoType: "Plan Video",
        pageViews: 78,
        videoPlays: 7,
        videoCompletes: 2,
        uniqueVisitors: 5,
        date: "6/1/2024",
      },
    ],
    items: {
      title: "Craig Realty Group Retirement Savings Plan",
      image: "/client-logo/craig_realty.png",
      eligibility: {
        waiting_period:
          "After 2 months of service employees age 21 or older can enter the plan at the beginning of the next calendar quarter",
      },
      employee_contributions: {
        auto_enrollment: "5%, after 2 months",
        auto_increase: "No",
        safe_harbor: "No",
        after_tax_contributions: "No",
        mandatory_contributions: "No",
        roth_contributions: "No",
      },
      employer_contributions: {
        match: "N/A",
        safe_harbor: "N/A",
        non_elective: "N/A",
        // waiting_period: "12 months, these contributions will begin on the next month",
        // waiting_period_sub: "1000 Hours, these contributions will begin on the next semi annual entry date"
      },
      vesting_and_operations: {
        vesting: "N/A",
        qdia: "Yes",
        target_date: "No",
        models: "No",
        loans_permitted: "Yes",
        hardships_permitted: "No",
        sd_brokerage_account: "No",
        managed_accounts: "No",
      },
      data: [
        {
          id: 1,
          title: "Plan Investment Advisor",
          subTitle: "Ty Rogers",
          email: "401ksupport@waypoint.com",
          phone: "(877) 757-3263",
          image: "/logo-2.png",
          icon: FileIcon,
        },
        {
          id: 2,
          title: "Account Access / Enroll",
          subTitle: "Transamerica",
          website: "https://transamerica.com",
          phone: "(800) 401-8726",
          image: "/transamerica.png",
          icon: KeyIcon,
        },
      ],
    },
  },
  {
    clientName: "G. Loomis ITI 401(k) Savings Plan",
    videoId: "7",
    fiduciaryTraining: "Status",
    lastModified: "8 days ago",
    clientColor: "#013365",
    image: "/client-logo/g_loomis.png",
    externalLink: "https://waypointfas.com/g-loomis/",
    isLegacyPlan: true,
    analytics: [
      {
        videoType: "Educational Video",
        pageViews: 59,
        videoPlays: 66,
        videoCompletes: 88,
        uniqueVisitors: 33,
        date: "5/31/2024",
      },
      {
        videoType: "Plan Video",
        pageViews: 78,
        videoPlays: 77,
        videoCompletes: 22,
        uniqueVisitors: 55,
        date: "6/1/2024",
      },
    ],
    items: {
      title: "G. Loomis ITI 401(k) Savings Plan",
      image: "/client-logo/g_loomis.png",
      eligibility: {
        waiting_period:
          "After hire, new employees age 18 or older are eligible to enter the plan at the beginning of the next month",
      },
      employee_contributions: {
        auto_enrollment: "No",
        auto_increase: "No",
        safe_harbor: "No",
        after_tax_contributions: "No",
        mandatory_contributions: "No",
        roth_contributions: "Yes",
      },
      employer_contributions: {
        match: "Fifty Percent Match, 6%",
        safe_harbor: "N/A",
        non_elective:
          "Discretionary Employer Contributions: discretionary & Discretionary Profit Sharing Contributions: discretionary",
        // waiting_period: "12 months, these contributions will begin on the next month",
        // waiting_period_sub: "1000 Hours, these contributions will begin on the next semi annual entry date"
      },
      vesting_and_operations: {
        vesting: "See Summary Plan",
        qdia: "Yes",
        target_date: "Yes",
        models: "Yes",
        loans_permitted: "No",
        hardships_permitted: "Yes",
        sd_brokerage_account: "No",
        managed_accounts: "No",
      },
      data: [
        {
          id: 1,
          title: "Plan Investment Advisor",
          subTitle: "Ty Rogers",
          email: "401ksupport@waypoint.com",
          phone: "(877) 757-3263",
          image: "/logo-2.png",
          icon: FileIcon,
        },
        {
          id: 2,
          title: "Account Access / Enroll",
          subTitle: "Fidelity",
          website: "https://netbenefits.com",
          phone: "(800) 343-0860",
          image: "/fidelity.png",
          icon: KeyIcon,
        },
        // {
        //   id: 3,
        //   title: "Human Resources",
        //   subTitle: "HR Person",
        //   email: "hr@person.com",
        //   phone: "(818) 555-5555",
        //   image: "",
        //   icon: PersonIcon,
        // },
      ],
    },
  },
  {
    clientName: "Shimano North America 401(k) Profit Sharing Plan",
    videoId: "8",
    fiduciaryTraining: "Status",
    lastModified: "1 day ago",
    clientColor: "#1345C1",
    image: "/client-logo/shimano.png",
    videoUrl:
      "https://synthesia-ttv-data.s3.amazonaws.com/video_data/076ad581-b13d-488a-a54a-d2b5769f6848/transfers/rendered_video.mp4?response-content-disposition=attachment%3Bfilename%3D%22Shimano%20Plan%20Details.mp4%22&AWSAccessKeyId=AKIA32NGJ5TSQOTYGMPR&Signature=68cYFSWC44VHDSh4Txjo6kzXjaw%3D&Expires=1732136499",
    externalLink: "https://waypointfas.com/shimano/",
    isLegacyPlan: true,
    analytics: [
      {
        videoType: "Educational Video",
        pageViews: 64,
        videoPlays: 33,
        videoCompletes: 44,
        uniqueVisitors: 77,
        date: "5/31/2024",
      },
      {
        videoType: "Plan Video",
        pageViews: 51,
        videoPlays: 22,
        videoCompletes: 66,
        uniqueVisitors: 44,
        date: "6/4/2024",
      },
    ],
    items: {
      title: "Shimano North America 401(k) Profit Sharing Plan",
      image: "/client-logo/shimano.png",
      eligibility: {
        waiting_period: "After hire, new employees are eligible to enter the plan at the beginning of the next month",
      },
      employee_contributions: {
        auto_enrollment: "No",
        auto_increase: "No",
        safe_harbor: "No",
        after_tax_contributions: "No",
        mandatory_contributions: "No",
        roth_contributions: "Yes",
      },
      employer_contributions: {
        match: "Fifty Percent Match, 6%",
        safe_harbor: "N/A",
        non_elective:
          "Discretionary Employer Contributions: discretionary & Discretionary Profit Sharing Contributions: 4%",
        waiting_period: "12 months, these contributions will begin on the next month",
        waiting_period_sub: "1000 Hours, these contributions will begin on the next semi annual entry date",
      },
      vesting_and_operations: {
        vesting: "5 Years",
        qdia: "Yes",
        target_date: "Yes",
        models: "Yes",
        loans_permitted: "Yes",
        hardships_permitted: "Yes",
        sd_brokerage_account: "No",
        managed_accounts: "No",
      },
      data: [
        {
          id: 1,
          title: "Plan Investment Advisor",
          subTitle: "Ty Rogers",
          email: "401ksupport@waypoint.com",
          phone: "(877) 757-3263",
          image: "/logo-2.png",
          icon: FileIcon,
        },
        {
          id: 2,
          title: "Account Access / Enroll",
          subTitle: "Fidelity",
          website: "https://netbenefits.com",
          phone: "(800) 343-0860",
          image: "/fidelity.png",
          icon: KeyIcon,
        },
      ],
    },
  },
  {
    clientName: "Air Fayre CA. Inc. 401(k) Plan",
    videoId: "10",
    fiduciaryTraining: "Status",
    lastModified: "1 day ago",
    clientColor: "#AB0634",
    image: "/client-logo/air_fayre.png",
    externalLink: "https://waypointfas.com/air-fayre/",
    isLegacyPlan: true,
    analytics: [
      {
        videoType: "Educational Video",
        pageViews: 24,
        videoPlays: 32,
        videoCompletes: 67,
        uniqueVisitors: 88,
        date: "5/31/2024",
      },
      {
        videoType: "Plan Video",
        pageViews: 58,
        videoPlays: 58,
        videoCompletes: 24,
        uniqueVisitors: 16,
        date: "6/1/2024",
      },
    ],
    items: {
      title: "Air Fayre CA. Inc. 401(k) Plan",
      image: "/client-logo/air_fayre.png",
      eligibility: {
        waiting_period: "After 3 months of service employees can enter the plan on the next payroll",
      },
      employee_contributions: {
        auto_enrollment: "No",
        auto_increase: "No",
        safe_harbor: "Yes",
        after_tax_contributions: "No",
        mandatory_contributions: "No",
        roth_contributions: "Yes",
      },
      employer_contributions: {
        // match: "Fifty Percent Match, 6%",
        safe_harbor: "100% match to 4%",
        non_elective:
          "Discretionary Employer Contributions: 4% & Discretionary Profit Sharing Contributions: discretionary",
        // waiting_period: "12 months, these contributions will begin on the next month",
        // waiting_period_sub: "1000 Hours, these contributions will begin on the next semi annual entry date"
      },
      vesting_and_operations: {
        vesting: "6 Year Graded",
        qdia: "Yes",
        target_date: "No",
        models: "Yes",
        loans_permitted: "Yes",
        hardships_permitted: "Yes",
        sd_brokerage_account: "No",
        managed_accounts: "No",
      },
      data: [
        {
          id: 1,
          title: "Plan Investment Advisor",
          subTitle: "Ty Rogers",
          email: "401ksupport@waypoint.com",
          phone: "(877) 757-3263",
          image: "/logo-2.png",
          icon: FileIcon,
        },
        {
          id: 2,
          title: "Account Access / Enroll",
          subTitle: "OneAmerica",
          website: "https://oneamerica.com",
          phone: "(800) 249-6269",
          planId: "G39156",
          image: "/one-america.png",
          icon: KeyIcon,
        },
        // {
        //   id: 3,
        //   title: "Human Resources",
        //   subTitle: "HR Person",
        //   email: "hr@person.com",
        //   phone: "(818) 555-5555",
        //   image: "",
        //   icon: PersonIcon,
        // },
      ],
    },
  },
  {
    clientName: "MJC Engineering & Technology Inc. 401(k) Profit Sharing Plan",
    videoId: "12",
    fiduciaryTraining: "Status",
    lastModified: "1 day ago",
    clientColor: "#0B264E",
    image: "/client-logo/mjc.png",
    externalLink: "https://waypointfas.com/mjc/",
    isLegacyPlan: true,
    analytics: [
      {
        videoType: "Educational Video",
        pageViews: 37,
        videoPlays: 46,
        videoCompletes: 52,
        uniqueVisitors: 64,
        date: "5/31/2024",
      },
      {
        videoType: "Plan Video",
        pageViews: 49,
        videoPlays: 87,
        videoCompletes: 38,
        uniqueVisitors: 63,
        date: "6/1/2024",
      },
    ],
    items: {
      title: "MJC Engineering & Technology Inc. 401(k) Profit Sharing Plan",
      image: "/client-logo/mjc.png",
      eligibility: {
        waiting_period:
          "After 3 months of service employees can enter the plan at the beginning of the next calendar quarter",
      },
      employee_contributions: {
        auto_enrollment: "No",
        auto_increase: "No",
        safe_harbor: "Yes",
        after_tax_contributions: "No",
        mandatory_contributions: "No",
        roth_contributions: "No",
      },
      employer_contributions: {
        // match: "N/A",
        safe_harbor: "Non Elective 3%",
        non_elective: "Discretionary Profit Sharing Contributions: discretionary",
      },
      vesting_and_operations: {
        vesting: "None",
        qdia: "Yes",
        target_date: "Yes",
        models: "No",
        loans_permitted: "Yes",
        hardships_permitted: "No",
        sd_brokerage_account: "No",
        managed_accounts: "No",
      },
      data: [
        {
          id: 1,
          title: "Plan Investment Advisor",
          subTitle: "Ty Rogers",
          email: "401ksupport@waypoint.com",
          phone: "(877) 757-3263",
          image: "/logo-2.png",
          icon: FileIcon,
        },
        {
          id: 2,
          title: "Account Access / Enroll",
          subTitle: "Transamerica",
          website: "https://transamerica.com",
          phone: "(800) 401-8726",
          image: "/transamerica.png",
          icon: KeyIcon,
        },
        {
          id: 3,
          title: "Point of Contact",
          subTitle: "Kristi Jensen",
          email: "kjensen@mjcengineering.com",
          phone: "(714) 890-0618",
          image: "/client-logo/mjc-2.png",
          icon: PersonIcon,
        },
      ],
    },
  },
  {
    clientName: "St. Mary & All Angels Christian Church 401(k) Plan",
    videoId: "13",
    fiduciaryTraining: "Status",
    lastModified: "2 days ago",
    clientColor: "#1345C1",
    image: "/client-logo/st_mary.png",
    externalLink: "https://waypointfas.com/st-marys/",
    isLegacyPlan: true,
    analytics: [
      {
        videoType: "Educational Video",
        pageViews: 22,
        videoPlays: 64,
        videoCompletes: 75,
        uniqueVisitors: 49,
        date: "5/31/2024",
      },
      {
        videoType: "Plan Video",
        pageViews: 63,
        videoPlays: 56,
        videoCompletes: 87,
        uniqueVisitors: 62,
        date: "6/1/2024",
      },
    ],
    items: {
      title: "St. Mary & All Angels Christian Church 401(k) Plan",
      image: "/client-logo/st_mary.png",
      eligibility: {
        waiting_period: "After 3 months of service employees can enter the plan at the beginning of the next month",
      },
      employee_contributions: {
        auto_enrollment: "4%, after 3 months",
        auto_increase: "No",
        safe_harbor: "Yes",
        after_tax_contributions: "No",
        mandatory_contributions: "No",
        roth_contributions: "Yes",
      },
      employer_contributions: {
        safe_harbor: "100% match to 4%",
        non_elective:
          "Discretionary Employer Contributions: discretionary & Discretionary Profit Sharing Contributions: discretionary",
      },
      vesting_and_operations: {
        vesting: "Immediate Vesting Schedule",
        qdia: "Yes",
        target_date: "Yes",
        models: "Yes",
        loans_permitted: "Yes",
        hardships_permitted: "Yes",
        sd_brokerage_account: "No",
        managed_accounts: "No",
      },
      data: [
        {
          id: 1,
          title: "Plan Investment Advisor",
          subTitle: "Ty Rogers",
          email: "401ksupport@waypoint.com",
          phone: "(877) 757-3263",
          image: "/logo-2.png",
          icon: FileIcon,
        },
        {
          id: 2,
          title: "Account Access / Enroll",
          subTitle: "OneAmerica",
          website: "https://oneamerica.com",
          phone: "(800) 249-6269",
          planId: "G38419",
          image: "/one-america.png",
          icon: KeyIcon,
        },
        // {
        //   id: 3,
        //   title: "Human Resources",
        //   subTitle: "HR Person",
        //   email: "hr@person.com",
        //   phone: "(818) 555-5555",
        //   image: "",
        //   icon: PersonIcon,
        // },
      ],
    },
  },
  {
    clientName: "Ocean Institute 401(k) Plan",
    videoId: "14",
    fiduciaryTraining: "Status",
    lastModified: "1 day ago",
    clientColor: "#1345C1",
    image: "/client-logo/ocean_institute.png",
    externalLink: "https://waypointfas.com/ocean-institute/",
    isLegacyPlan: true,
    analytics: [
      {
        videoType: "Educational Video",
        pageViews: 36,
        videoPlays: 28,
        videoCompletes: 44,
        uniqueVisitors: 51,
        date: "5/31/2024",
      },
      {
        videoType: "Plan Video",
        pageViews: 79,
        videoPlays: 85,
        videoCompletes: 97,
        uniqueVisitors: 69,
        date: "6/1/2024",
      },
    ],
    items: {
      title: "Ocean Institute 401(k) Plan",
      image: "/client-logo/ocean_institute.png",
      eligibility: {
        waiting_period:
          "After 6 months of service employees age 18 or older can enter the plan at the beginning of the next month",
      },
      employee_contributions: {
        auto_enrollment: "No",
        auto_increase: "No",
        safe_harbor: "No",
        after_tax_contributions: "No",
        mandatory_contributions: "No",
        roth_contributions: "Yes",
      },
      employer_contributions: {
        match: "N/A",
        safe_harbor: "N/A",
        non_elective: "N/A",
      },
      vesting_and_operations: {
        vesting: "N/A",
        qdia: "Yes",
        target_date: "Yes",
        models: "Yes",
        loans_permitted: "Yes",
        hardships_permitted: "Yes",
        sd_brokerage_account: "No",
        managed_accounts: "No",
      },
      data: [
        {
          id: 1,
          title: "Plan Investment Advisor",
          subTitle: "Ty Rogers",
          email: "401ksupport@waypoint.com",
          phone: "(877) 757-3263",
          image: "/logo-2.png",
          icon: FileIcon,
        },
        {
          id: 2,
          title: "Account Access / Enroll",
          subTitle: "OneAmerica",
          website: "https://oneamerica.com",
          phone: "(800) 249-6269",
          planId: "G38768",
          image: "/one-america.png",
          icon: KeyIcon,
        },
      ],
    },
  },
]

export const navItems: NavItem[] = [
  {
    title: "Dashboard",
    href: "/new/dashboard",
    icon: "dashboard",
    label: "Dashboard",
  },
  {
    title: "Plans",
    href: "/clients",
    icon: "users",
    label: "Plans",
    items: [
      {
        title: "View Plans",
        href: "/new/clients",
        label: "All Plans",
      },
      {
        title: "Create Plan",
        href: "/new/new-client",
        label: "Create New Plan",
      },
    ],
  },
  {
    title: "Communications",
    href: "/new/communications",
    icon: "megaphone",
    label: "Communications",
    items: [
      {
        title: "Meetings",
        href: "/new/meetings",
        label: "Meetings",
      },
      {
        title: "Webinars & Replays",
        href: "/new/meetings/webinars",
        label: "Webinars & Replays",
      },
      {
        title: "Marketing",
        href: "/new/marketing",
        label: "Marketing",
      },
    ],
  },
  {
    title: "Documents",
    href: "/new/documents",
    icon: "fileText",
    label: "Documents",
  },
  {
    title: "Video",
    href: "/new/video",
    icon: "play",
    label: "Video",
    items: [
      {
        title: "View Videos",
        href: "/new/videos",
        label: "View Videos",
      },
      {
        title: "Create Video",
        href: "/new/video",
        label: "Create Video",
      },
    ],
  },
  {
    title: "Create Benefits",
    href: "/new/benefits",
    icon: "wand-sparkles",
    label: "CreateBenefits",
  },
  {
    title: "Settings",
    href: "/new/settings",
    icon: "settings",
    label: "Settings",
  },
]

export const recordKeepers = [
  {
    id: "1",
    name: "401Go",
    website: "https://401go.com",
    phone: "(801) 214-2125",
    image: "/401go.png",
  },
  {
    id: "2",
    name: "ADP Retirement Services",
    website: "https://mykplan.com",
    phone: "(800) 695-7526",
    image: "/adp.png",
  },
  {
    id: "3",
    name: "AMI Benefit",
    website: "https://amibenefit.com",
    phone: "(800) 451-2865",
    image: "/ami_benefit.png",
  },
  {
    id: "4",
    name: "APB Retirement",
    website: "https://yourbenefitaccount.com",
    phone: "(800) 480-5190",
    image: "/apb_retirement.png",
  },
  {
    id: "5",
    name: "Alerus",
    website: "https://login.alerus.com",
    phone: "(800) 433-1685",
    image: "/alerus.png",
  },
  {
    id: "6",
    name: "American Funds",
    website: "https://americanfunds.com",
    phone: "(800) 421-4120",
    image: "/american_funds.png",
  },
  {
    id: "7",
    name: "American Funds (PlanPremier)",
    website: "https://myretirement.americanfunds.com",
    phone: "(800) 204-3731",
    image: "/american_funds.png",
  },
  {
    id: "8",
    name: "American Funds (RecordKeeperDirect)",
    website: "https://americanfunds.com",
    phone: "(800) 421-4120",
    image: "/american_funds.png",
  },
  {
    id: "9",
    name: "Ameritas",
    website: "https://accounts.ameritas.com",
    phone: "(800) 277-9739",
    image: "/ameritas.png",
  },
  {
    id: "10",
    name: "Ascensus",
    website: "https://myaccount.ascensus.com",
    phone: "(888) 652-8086",
    image: "/ascensus.png",
  },
  {
    id: "11",
    name: "Ascensus (Newport Transition)",
    website: "https://secure.ascensus.com",
    phone: "(844) 749-9981",
    image: "/ascensus_newport.png",
  },
  {
    id: "12",
    name: "BB&T",
    website: "https://bbt.com",
    phone: "(800) 228-8076",
    image: "/bbt.png",
  },
  {
    id: "13",
    name: "BPAS",
    website: "https://bpas.com",
    phone: "(866) 401-5272",
    image: "/bpas.png",
  },
  {
    id: "14",
    name: "Charles Schwab",
    website: "https://workplace.schwab.com",
    phone: "(800) 724-7526",
    image: "/charles_schwab.png",
  },
  {
    id: "15",
    name: "Cuna Mutual",
    website: "https://benefitsforyou.com",
    phone: "(800) 356-2644",
    image: "/cuna_mutual.png",
  },
  {
    id: "16",
    name: "EPIC",
    website: "https://go-retire.com",
    phone: "(800) 716-3742",
    image: "/epic.png",
  },
  {
    id: "17",
    name: "Employee Fiduciary",
    website: "https://retirementlogin.net",
    phone: "(877) 401-5100",
    image: "/employee_fiduciary.png",
  },
  {
    id: "18",
    name: "Empower",
    website: "https://participant.empower-retirement.com",
    phone: "(800) 338-4015",
    image: "/empower.png",
  },
  {
    id: "19",
    name: "Empower (RetireSmart)",
    website: "https://retiresmart.com",
    phone: "(888) 526-6905",
    image: "/empower_retiresmart.png",
  },
  {
    id: "20",
    name: "Fidelity (401k.com)",
    website: "https://401k.com",
    phone: "(800) 835-5097",
    image: "/fidelity.png",
  },
  {
    id: "21",
    name: "Fidelity (netbenefits)",
    website: "https://netbenefits.com",
    phone: "(800) 343-0860",
    image: "/fidelity.png",
  },
  {
    id: "22",
    name: "Goldman Sachs",
    website: "https://myaccount.ascensus.com",
    phone: "(888) 652-8086",
    image: "/goldman_sachs.png",
  },
  {
    id: "23",
    name: "Human Interest",
    website: "https://app.humaninterest.com",
    phone: "(855) 622-7824",
    image: "/human_interest.png",
  },
  {
    id: "24",
    name: "Insperity",
    website: "https://retirement.insperity.com",
    phone: "(866) 715-3552",
    image: "/insperity.png",
  },
  {
    id: "25",
    name: "J.P. Morgan",
    website: "https://retirementlink.jpmorgan.com",
    phone: "(855) 576-7526",
    image: "/jp_morgan.png",
  },
  {
    id: "26",
    name: "John Hancock",
    website: "https://myplan.johnhancock.com",
    phone: "(800) 395-1113",
    image: "/john_hancock.png",
  },
  {
    id: "27",
    name: "LT Trust",
    website: "https://401k.itretire.com",
    phone: "(800) 831-8675",
    image: "/lt_trust.png",
  },
  {
    id: "28",
    name: "Lincoln Financial Group",
    website: "https://lincolnfinancial.com",
    phone: "(800) 234-3500",
    image: "/lincoln_financial.png",
  },
  {
    id: "29",
    name: "Lincoln Financial Group (Director Plans)",
    website: "https://lincolnfinancial.com",
    phone: "(800) 510-4015",
    image: "/lincoln_financial.png",
  },
  {
    id: "30",
    name: "Mass Mutual/Empower",
    website: "https://retiresmart.com",
    phone: "(800) 338-4015",
    image: "/mass_mutual_empower.png",
  },
  {
    id: "31",
    name: "Merrill Lynch",
    website: "https://mymerrill.com",
    phone: "(800) 637-7455",
    image: "/merrill_lynch.png",
  },
  {
    id: "32",
    name: "Mutual of America",
    website: "https://myaccount.mutualofamerica.com",
    phone: "(800) 468-3785",
    image: "/mutual_of_america.png",
  },
  {
    id: "33",
    name: "Mutual of Omaha",
    website: "https://accounts.mutualofomaha.com",
    phone: "(888) 917-7191",
    image: "/mutual_of_omaha.png",
  },
  {
    id: "34",
    name: "NWPS",
    website: "https://yourplanaccess.net",
    phone: "(888) 700-0808",
    image: "/nwps.png",
  },
  {
    id: "35",
    name: "Nationwide",
    website: "https://nationwide.com",
    phone: "(877) 677-3678",
    image: "/nationwide.png",
  },
  {
    id: "36",
    name: "Newport Group",
    website: "https://secure.newportgroup.com",
    phone: "(844) 749-9981",
    image: "/newport_group.png",
  },
  {
    id: "37",
    name: "OneAmerica",
    website: "https://oneamerica.com",
    phone: "(800) 249-6269",
    image: "/oneamerica.png",
  },
  {
    id: "38",
    name: "OneAmerica (Trust)",
    website: "https://oaretirement.com",
    phone: "(800) 858-3829",
    image: "/oneamerica.png",
  },
  {
    id: "39",
    name: "P&A Group",
    website: "https://pag.retirement.schwabrt.com",
    phone: "(716) 852-2611",
    image: "/pa_group.png",
  },
  {
    id: "40",
    name: "PCS Retirement",
    website: "https://pcs401k.com",
    phone: "(888) 621-5491",
    image: "/pcs_retirement.png",
  },
  {
    id: "41",
    name: "Paychex",
    website: "https://paychexflex.com",
    phone: "(877) 244-1771",
    image: "/paychex.png",
  },
  {
    id: "42",
    name: "Penserv",
    website: "https://secure.penserv.com",
    phone: "(800) 849-4001",
    image: "/penserv.png",
  },
  {
    id: "43",
    name: "Principal",
    website: "https://principal.com",
    phone: "(800) 547-7754",
    image: "/principal.png",
  },
  {
    id: "44",
    name: "Prudential",
    website: "https://prudential.com",
    phone: "(800) 824-0040",
    image: "/prudential.png",
  },
  {
    id: "45",
    name: "Retirement Plan Consultants",
    website: "https://yourplanaccess.net",
    phone: "(877) 800-1114",
    image: "/rpc.png",
  },
  {
    id: "46",
    name: "Securian Financial",
    website: "https://securianretirementcenter.com",
    phone: "(800) 233-2881",
    image: "/securian.png",
  },
  {
    id: "47",
    name: "Security Benefit",
    website: "https://securitybenefit.com",
    phone: "(800) 747-3942",
    image: "/security_benefit.png",
  },
  {
    id: "48",
    name: "Sentinel Group",
    website: "https://sentinelgroup.com",
    phone: "(888) 762-6088",
    image: "/sentinel_group.png",
  },
  {
    id: "49",
    name: "Slavic401k",
    website: "https://slavic401k.com",
    phone: "(800) 356-3009",
    image: "/slavic401k.png",
  },
  {
    id: "50",
    name: "Standard",
    website: "https://standard.com",
    phone: "(800) 858-5420",
    image: "/standard.png",
  },
  {
    id: "51",
    name: "T. Rowe Price",
    website: "https://rps.troweprice.com",
    phone: "(800) 922-9945",
    image: "/t_rowe_price.png",
  },
  {
    id: "52",
    name: "TIAA",
    website: "https://tiaa.org",
    phone: "(800) 842-2252",
    image: "/tiaa.png",
  },
  {
    id: "53",
    name: "Touchstone Retirement Group",
    website: "https://tsretirement.com",
    phone: "(877) 937-2040",
    image: "/touchstone.png",
  },
  {
    id: "54",
    name: "Transamerica",
    website: "https://transamerica.com",
    phone: "(800) 401-8726",
    image: "/transamerica.png",
  },
  {
    id: "55",
    name: "Trusted Capital Group",
    website: "https://tcgservices.com",
    phone: "(512) 600-5200",
    image: "/trust.png",
  },
  {
    id: "56",
    name: "Vanguard 403(b)",
    website: "https://vanguard403bservices.com",
    phone: "(800) 569-4903",
    image: "/vanguard.png",
  },
  {
    id: "57",
    name: "Vanguard (Direct)",
    website: "https://retirementplans.vanguard.com",
    phone: "(800) 523-1188",
    image: "/vanguard.png",
  },
  {
    id: "58",
    name: "Vanguard (VRPA)",
    website: "https://myvanguardplan.com",
    phone: "(866) 794-2145",
    image: "/vanguard.png",
  },
  {
    id: "59",
    name: "Vestwell",
    website: "https://signin.vestwell.com",
    phone: "(800) 584-6001",
    image: "/vestwell.png",
  },
  {
    id: "60",
    name: "Voya Financial",
    website: "https://voyaretirementplans.com",
    phone: "(800) 584-6001",
    image: "/voya.png",
  },
  {
    id: "61",
    name: "WeLLthBuilder",
    website: "https://wellthbuilder.vestwell.com",
    phone: "(917) 979-5358 ext.1",
    image: "/wellthbuilder.png",
  },
  {
    id: "62",
    name: "Wells Fargo",
    website: "https://wellsfargo.com",
    phone: "(800) 728-3123",
    image: "/wells.png",
  },
  { id: "63", name: "Custom", image: "/custom.png" },
]

export const IMG_MAX_LIMIT = 1;

